// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('t1', { text: 'Entities' });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateScrollArea('scrollArea', { spacing: 4, hasVerticalScrollbar: true, autoHideScrollbars: true });
    CreateText('link', { text: 'By Left Logic' });
    CreateText('text', { text: 'Feel free to leave feedback or comments.' });
}
window.addEventListener('load', setupParts, false);
